# Generated by Django 2.1 on 2020-04-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('S_Admin', '0003_restauranttypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=64)),
                ('restaurant_contact', models.IntegerField()),
                ('restaurant_email', models.EmailField(max_length=254)),
                ('restaurant_password', models.CharField(max_length=64)),
                ('restaurant_otp', models.IntegerField()),
                ('restaurant_status', models.CharField(max_length=32)),
                ('restaurant_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_Admin.AreaModel')),
                ('restaurant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_Admin.RestaurantTypeModel')),
            ],
        ),
    ]
